import type { Metadata } from "next";
import "./globals.css";
import { geistSans, geistMono, vazir, shabnam } from "./ui/font";
import NextIntlProvider from "./providers";



export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className}`}>
        <NextIntlProvider>
            {children}
        </NextIntlProvider>
      </body>
    </html>
  );
}
